name: AutoUpdate
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  AutoUpdate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: liveview
      - name: Config name
        run: git config user.name github-actions
      - name: Config email
        run: git config user.email github-actions@github.com
      - name: Fetch
        run: git fetch
      - name: Rebase
        run: git rebase -Xtheirs origin/staging
      - name: Reset
        run: git reset --hard origin/staging
      - name: Update
        run: python3 Update.py
      - name: Add
        run: git add .
      - name: Commit
        run: git commit -m "Auto Update data files"
      - name: Push
        run: git push --force

