name: AutoUpdate
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  AutoUpdate:
    runs-on: ubuntu-latest
    steps:
    
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: liveview
          
      - name: Fetch, Rebase, Reset, Update, Commit, and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git rebase origin/staging
          git reset HEAD~1
          python3 Update.py
          git add .
          git commit -m "Auto Update data files"
          git push --force

